export const previous = document.querySelector(".pager_previous");
export const next = document.querySelector(".pager_next");
export const upValue = document.querySelector(".manager_content .manager_items");
export const pagerValue= document.querySelector(".pager_counter .pager-value");
export const pagerLimit= document.querySelector(".pager_counter .pager_limit");
export const inputSearch = document.querySelector(".search .employess__input");
export const sortValue = document.querySelector('.filter');
export const inputItem = document.querySelector('.left_input');
export const emailItem = document.querySelector('.left_email');
export const jobItem = document.querySelector('.left_job');
export const countItem = document.querySelector('.left_count');
export const addItem = document.querySelector('.left_btn');
export const selectPerpage = document.querySelector('.select')
export const modal =document.querySelector('.js-modal')
export const modalClose=document.querySelector('.js-modal-close')
export const modalContainer=document.querySelector('.js-modal-container')
export const addItems = document.querySelector('.add__item')
export const inputItemModal = document.querySelector('.left_inputs')
export const modalCount = document.querySelector('.modal_left')
export const modalJob = document.querySelector('.left_jobs')
export const modalEmail = document.querySelector('.modal_email')
export const addBtnModal = document.querySelector('.left_btns')